# finally 代码块

## 概述

+ `try...catch` 结构允许在最后添加一个 `finally` 代码块，表示不管是否出现错误，都必需在最后运行的语句

  ```js
  function cleansUp() {
    try {
      throw new Error('出错了……');
      console.log('此行不会执行');
    } finally {
      console.log('完成清理工作');
    }
  }

  cleansUp()
  // 完成清理工作
  // Uncaught Error: 出错了……
  //    at cleansUp (<anonymous>:3:11)
  //    at <anonymous>:10:1
  ```
