# 基础

## 概述

+ 异常就是不正常
+ 当 Python 检测到一个错误的时候，解释器就无法继续执行下去了，反而出现了一些错误提示，这就使异常

## 语法

+ 语法

  ```py
  try:
    ...
  except 异常1:
  except 异常2:
  except 异常3:
  ```

+ 多个异常之间的顺序要求：子类在前，父类在后

  ```py
  def div(a, b):
      try:
          intA = int(a)
          intB = int(b)
          c = a / b
          # return c
          print(c)
      except ValueError:
          print('数据类型错误')
      except ZeroDivisionError:
          print('除数不能为0')
      except Exception:
          print('其他异常')

  print(div(10, 0))
  ```

## 多个异常

+ 方式1

  + 多个异常之间的顺序要求：子类在前，父类在后

  ```py
  def div(a, b):
      try:
          intA = int(a)
          intB = int(b)
          c = a / b
          # return c
          print(c)
      except ValueError:
          print('数据类型错误')
      except ZeroDivisionError:
          print('除数不能为0')
      except Exception:
          print('其他异常')


  print(div(10, 0))
  ```

+ 方式2：使用元组存储。则多个异常之间没有顺序要求

  ```py
  def div(a, b):
      try:
          intA = int(a)
          intB = int(b)
          c = a / b
          # return c
          print(c)
      except (ValueError, ZeroDivisionError, Exception) as e:
          print('错误类型', e)


  print(div(10, 0))
  ```
